<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>postDistance</name>
   <tag></tag>
   <elementGuidId>4afe21d8-74d0-4e6a-a101-c39c31484411</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  "contentType": "application/json",
  "charset": "UTF-8",
  "text": "{\\n  \\\"from\\\": \\\"${from}\\\",\\n  \\\"to\\\": \\\"${to}\\\"\\n}"
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <katalonVersion>10.4.2</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://airportgap.com/api/airports/distance</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
   <variables>
      <defaultValue>KIX</defaultValue>
      <description></description>
      <id>from</id>
      <masked>false</masked>
      <name>from</name>
   </variables>
   <variables>
      <defaultValue>NRT</defaultValue>
      <description></description>
      <id>to</id>
      <masked>false</masked>
      <name>to</name>
   </variables>
</WebServiceRequestEntity>
